smoke_list=
large_data_list=dataCompress,mthMatch_large_data,cappedCL_Large_Data,sortOptimize_largeData
sync_list=backupRestore_rlb,vote_rlb,sdbLobTool_auth,jsObjectSync,jsObject_rlb,forceSession,reloadConf_rlb,analyze_sync,analyze_rlb,sdbexprt_auth,getSlave_rlb,sdb_sync,sdb_rlb,sessionAccess,sessionAccess_rlb,healthSnap,dbClasses,dbClasses_rlb,configs,configs_rlb,rest_analyze_sync,rest_conf_sync,clsMgr,clsMgr_rlb,subCL_rlb,rename,fulltext_sync,split_rlb,query_rlb,fulltext_rlb,transaction_sync,list_sync,snapshot_rlb,resetSnapshot,clearAccessPlanCache_sync,sql_sync,auth,transaction_rlb,analyze,location_rlb
configure_list=sdbLobTool_ssl,dataTypeEnableCmpMode_config,rest_conf,sdbexprt_ssl,sdbreplay
reliability_list=
common_list=lib
runtest_ignoredpaths=fulltext
