smoke_list=
large_data_list=dataCompress,mthMatch_large_data,sortOptimize
sync_list=backupRestore,vote,sdbLobTool_auth,jsObjectSync,forceSession,reloadConf,sdbexprt_auth,sessionAccess,sdb_sync,clsMgr,dataSyn,subCL_sync
configure_list=transaction,sdbLobTool_ssl,rest_conf,sdbexprt_ssl
reliability_list=sdbLobTool_reliable
common_list=lib
