#!/bin/bash

# author: Ting YU 2021-04-09

#   error code list:
#   64    command line usage error

function err_para()
{
   local para_name="$1"
   local para_value="$2"
   echo "sdbupgradeidx: unrecognized $para_name \"$para_value\"" >&2
   echo 'Try "sdbupgradeidx --help" for more information.'
   exit 64
}

function check_num_para()
{
   local para_name=$1
   local para_value=$2

   local regex='^[0-9]+$'
   if ! [[ "$para_value" =~ $regex ]]; then
      echo "sdbtaskctl: invalid value for parameter \"$para_name\": \"$para_value\"" >&2
      echo 'Try "sdbtaskctl --help" for more information.'
      exit 64
   fi
}

function show_version()
{
   echo "sdbupgradeidx: "$DB_VERSION
   echo "Release: "$RELEASE
   echo "Git version: "$GIT_VERSION
   echo $BUILD_TIME
}

function build_help()
{
   echo "sdbupgradeidx is a utility to upgrade index."
   echo ""
   echo "Common options:"
   echo "  -s [ --hostname ] arg        host name, default: localhost"
   echo "  -p [ --svcname ] arg         service name, default: 11810"
   echo "  -o [ --output ] arg          specify the output file"
   echo "  --action arg                 check or upgrade, defalut: check"
   echo "  -h [ --help ]                print help message"
   echo "  --version                    print version information"
   echo ""
   echo "Example: "
   echo "  ./sdbupgradeidx -s localhost -p 11810 --action check"
   echo ""
}

##################################
#    main entry
##################################

# The autogen will replace the following 4 values.
DB_VERSION="x.x.x"
RELEASE="0"
GIT_VERSION="xxxxxxxxxx"
BUILD_TIME="0000-00-00-00.00.00"

# Default value
HOSTNAME="localhost"
SVCNAME=11810
OUTPUT="./sdbupgradeidx.log"
ACTION="check"

# Parse command line parameters
test $# -eq 0 && { build_help && exit 64; }

ARGS=`getopt -o hs:p:o: --long help,version,hostname:,svcname:,output:,action: -n 'sdbupgradeidx' -- "$@"`
ret=$?
test $ret -ne 0 && exit $ret

eval set -- "${ARGS}"

while true
do
   case "$1" in
      --action )          ACTION="$2"
                          test "$ACTION" == "check" -o "$ACTION" == "upgrade" \
                             || err_para ACTION "$ACTION"
                          shift 2
                          ;;
      -s | --hostname )   HOSTNAME=$2
                          shift 2
                          ;;
      -p | --svcname )    SVCNAME=$2
                          check_num_para "SVCNAME" "$SVCNAME"
                          shift 2
                          ;;
      -o | --output )     OUTPUT=$2
                          shift 2
                          ;;
      --version )         show_version
                          exit 0
                          ;;
      -h | --help )       build_help
                          exit 0
                          ;;
      --)                 shift
                          break
                          ;;
      *)                  echo "Internal error!"
                          exit 64
                          ;;
   esac
done

if [ "$*" != "" ]; then
   echo "sdbupgradeidx: too many arguments: $*" >&2
   echo 'Try "sdbupgradeidx --help" for more information.'
   exit 64
fi

# get this script path
myPath=`dirname $0`

if [[ ${myPath:0:1} != "/" ]]; then
   myPath=$(pwd)/$myPath  #relative path
else
   myPath=$myPath         #absolute path
fi

# get sdb shell path
sdbShellPath=$myPath/../../bin/sdb

# get upgradeIndex.js path
jsFile=$myPath/upgradeIndex.js

# generate parameters
jsParameter="var hostname=\""$HOSTNAME"\";"
jsParameter=$jsParameter"var svcname="$SVCNAME";"
if [ "$ACTION" == "check" ]; then
   jsParameter=$jsParameter"var checkonly=true;"
else
   jsParameter=$jsParameter"var checkonly=false;"
fi

jsParameter="'"$jsParameter"'"

# execute command
command=$sdbShellPath" -f "$jsFile" -e "$jsParameter" > "$OUTPUT
#echo "Execute command: "$command
eval $command
echo "Generate report: "$OUTPUT

exit 0
