var tmpGlobal = {
   catPath: catPath,
   forceGC: forceGC,
   getExePath: getExePath,
   getLastErrMsg: getLastErrMsg,
   getLastErrObj: getLastErrObj,
   getLastError: getLastError,
   getRootPath: getRootPath,
   getSelfPath: getSelfPath,
   print: print,
   setLastErrMsg: setLastErrMsg,
   setLastErrObj: setLastErrObj,
   setLastError: setLastError,
   showClass: showClass,
   showClassfull: showClassfull,
   sleep: sleep,
   traceFmt: traceFmt
};
catPath=function(){try{return tmpGlobal.catPath.apply(this,arguments);}catch(e){commThrowError(e)}};
forceGC=function(){try{return tmpGlobal.forceGC.apply(this,arguments);}catch(e){commThrowError(e)}};
getExePath=function(){try{return tmpGlobal.getExePath.apply(this,arguments);}catch(e){commThrowError(e)}};
getLastErrMsg=function(){try{return tmpGlobal.getLastErrMsg.apply(this,arguments);}catch(e){commThrowError(e)}};
getLastErrObj=function(){try{return tmpGlobal.getLastErrObj.apply(this,arguments);}catch(e){commThrowError(e)}};
getLastError=function(){try{return tmpGlobal.getLastError.apply(this,arguments);}catch(e){commThrowError(e)}};
getRootPath=function(){try{return tmpGlobal.getRootPath.apply(this,arguments);}catch(e){commThrowError(e)}};
getSelfPath=function(){try{return tmpGlobal.getSelfPath.apply(this,arguments);}catch(e){commThrowError(e)}};
print=function(){try{return tmpGlobal.print.apply(this,arguments);}catch(e){commThrowError(e)}};
setLastErrMsg=function(){try{return tmpGlobal.setLastErrMsg.apply(this,arguments);}catch(e){commThrowError(e)}};
setLastErrObj=function(){try{return tmpGlobal.setLastErrObj.apply(this,arguments);}catch(e){commThrowError(e)}};
setLastError=function(){try{return tmpGlobal.setLastError.apply(this,arguments);}catch(e){commThrowError(e)}};
showClass=function(){try{return tmpGlobal.showClass.apply(this,arguments);}catch(e){commThrowError(e)}};
showClassfull=function(){try{return tmpGlobal.showClassfull.apply(this,arguments);}catch(e){commThrowError(e)}};
sleep=function(){try{return tmpGlobal.sleep.apply(this,arguments);}catch(e){commThrowError(e)}};
traceFmt=function(){try{return tmpGlobal.traceFmt.apply(this,arguments);}catch(e){commThrowError(e)}};
