EnsureSConsVersion( 1, 1, 0 )
import platform
import os
import re
from os.path import join, dirname, abspath

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")
Import("client_lib_dir")

gtestFiles = [
   "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc"
]

gtestMainFile = [
   "../../../../../SequoiaDB/engine/gtest/src/gtest_main.cc"
]

clientStaticLib = [
   client_lib_dir + "/libstaticsdbc.a"
]

testCommonFiles = [
   "./common/testcommon.cpp",
   "./common/impWorker.cpp"
]

clientStaticLibFile = join( client_lib_dir, 'libstaticsdbc.a' )

testFiles = [ 
   [ "./misc/decimal.cpp" ],
   [ "./misc/numberLong.cpp" ],
   [ "./misc/trunOncache.cpp" ],
   [ "./misc/restAbnormal.cpp" ],
   [ "./misc/procedure.cpp" ],
   #[ "./misc/socketMutex.cpp" ],
   [ "./misc/index.cpp" ],
   [ "./misc/dropCsAndWriteLob.cpp" ],
   [ "./misc/idIndex.cpp" ],
   [ "./misc/attachAndDetachNode.cpp" ], # sync
   [ "./misc/forceSession.cpp" ], # sync
   [ "./misc/JSCompatible.cpp" ],
   [ "./misc/code.cpp" ],
   [ "./misc/bson_oid.cpp" ],
   [ "./misc/date.cpp" ],
   [ "./misc/bson_array.cpp" ],
   [ "./misc/snapshotTrans.cpp" ], # conf
   [ "./misc/masterSlave.cpp" ], # sync
   [ "./misc/snapshotSys14118.cpp" ],
   [ "./concurrent/concurrentCs.cpp" ],
   [ "./concurrent/concurrentCl.cpp" ],
   [ "./concurrent/concurrentLob.cpp" ],
   [ "./concurrent/concurrentCursor.cpp" ],
   [ "./concurrent/concurrentNode.cpp" ], # sync
   [ "./concurrent/concurrentRg.cpp" ], # sync
   [ "./lob/lobNormal.cpp" ],
   [ "./lob/lobAbnormal.cpp" ],
   [ "./ssl/sslFalse.cpp" ],
   [ "./ssl/sslTrue.cpp" ], # conf
   [ "./load/loadUnloadCS.cpp" ],
   [ "./load/rename.cpp" ],
   [ "./load/setPDLevel.cpp" ], # sync
   [ "./crud/queryMeta.cpp" ],
   [ "./crud/specialDecimal_14004.cpp" ],
   [ "./paraVerify/lobFunc14388.cpp" ],
   [ "./paraVerify/sdbFunc14277.cpp" ],
   [ "./paraVerify/clFunc14281.cpp" ],
   [ "./sessionAttr/instanceid14158.cpp" ], # sync
   [ "./crud/insertReplaceondup18581.cpp" ],
   [ "./auth/createUsr17941_17957.cpp" ],  # sync
   [ "./crud/query10404.cpp" ],
   [ "./list/list19948.cpp" ]  # sync
]

def getFileName( filePath ):
   strArr = re.split( r'[/.]', filePath )
   # last element is suffix,
   # second last element is the name
   return strArr[-2]

def getObjectName( filePath ):
   return getFileName( filePath ) + ".o"

# add common to path
dllBuildEnv.Append( CPPPATH=[ "./common/" ] )
staticBuildEnv.Append( CPPPATH=[ "./common/" ] )

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)

# complit main object file
testMainObj = dllBuildEnv.Object( [gtestMainFile] )

# compile common object file
commObj = []
for file in testCommonFiles:
   commonFileName = getFileName( file )
   commonFile = dllBuildEnv.Object( commonFileName, [file] )
   commObj.append( commonFile )

# compile test object file
objectFiles = []
for index in range( len(testFiles) ):
   objectFileArr = []
   for file in testFiles[index]:
      objectFileName = getObjectName( file )
      objectFile = dllBuildEnv.Object( objectFileName, [file] )
      objectFileArr.append( objectFile )
   objectFiles.append( objectFileArr )

# dll compile
dllPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] )
   dllProgram = dllBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj] )
   dllPrograms.append( dllProgram )

# static compile
staticPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] ) + ".static"
   staticProgram = staticBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj])
   staticPrograms.append( staticProgram )

# dll compile
env.Install( '#/build_test', dllPrograms )

# static compile
env.Install( '#/build_test', staticPrograms )
