X86_NORMALTEST_G3D3_HOST       =test-ci-ubun2,test-ci-ubun4,test-ci-ubun5
X86_NORMALTEST_G1D3_HOST       =test-ci-rhel5,test-ci-rhel6,test-ci-rhel7
X86_NORMALTEST_STANDALONE_HOST =test-ci-suse6

X86_LARGEDATATEST_G3D3_HOST    =ci-test-suse10,ci-test-suse11,ci-test-suse12
X86_SYNCTEST_G3D3_HOST         =test-ci-cent5,test-ci-cent6,test-ci-cent7
X86_CONFIGURETEST_G3D3_HOST    =test-ci-cent5,test-ci-cent6,test-ci-cent7
X86_RELIABILITYTEST_G3D3_HOST  =test-ci-rhel4,test-ci-ubun1,test-ci-cent4
X86_SMOKETEST_G3D3_HOST        =ci-test-rhel3,jenkins-master,ci-test-ubun8

PPC_NORMALTEST_G3D3_HOST       =ci-test-ppc-rhel2,ci-test-ppc-rhel1,ci-test-ppc-suse1
PPC_NORMALTEST_G1D3_HOST       =ci-test-ppc-rhel2,ci-test-ppc-rhel1,ci-test-ppc-suse1
PPC_NORMALTEST_STANDALONE_HOST =ci-test-ppc-rhel2

PERFORMANCETEST_TPCC_HOST      =ci-test-pm1,ci-test-pm2,ci-test-pm3

INSTALL_DIR=/opt/sequoiadb
INSTALL_PG_DIR=/opt/SequoiaSQL
CI_WORK_DIR=/tmp/ci
SVCNAME=11810
RELIABILITY_TESTCASE_WORK_DIR=/tmp/ci_reliability

BACKLOG_DIR=/opt/ci/backup_log
JENKINS_HOST=test-ci-suse10

DOC_HOST=ci-cmpl-doc

TPCC_DBPATH_LIST = /data/disk01/sequoiadb,/data/disk02/sequoiadb,/data/disk03/sequoiadb,/data/disk04/sequoiadb,/data/disk05/sequoiadb,/data/disk06/sequoiadb,/data/disk07/sequoiadb,/data/disk08/sequoiadb,/data/disk09/sequoiadb,/data/disk10/sequoiadb,/data/disk11/sequoiadb,/data/disk12/sequoiadb,
RELIABILITYTEST_DBPATH_LIST=/data/sequoiadb



