X86_NORMALTEST_G3D3_HOST       =ci-test-suse2,ci-test-cent2,ci-test-ubun7
X86_NORMALTEST_G1D3_HOST       =ci-test-cent1,ci-test-suse3,ci-test-rhel2
X86_NORMALTEST_STANDALONE_HOST =ci-test-suse1

X86_LARGEDATATEST_G3D3_HOST    =ci-test-suse10,ci-test-suse11,ci-test-suse12
X86_SYNCTEST_G3D3_HOST         =ci-test-rhel1,ci-test-cent3,ci-test-ubun6
X86_CONFIGURETEST_G3D3_HOST    =ci-test-rhel1,ci-test-cent3,ci-test-ubun6
X86_RELIABILITYTEST_G3D3_HOST  =ci-test-rhel4,ci-test-ubun1,ci-test-cent4
X86_SMOKETEST_G3D3_HOST        =ci-test-rhel3,jenkins-master,ci-test-ubun8

PPC_NORMALTEST_G3D3_HOST       =ci-test-ppc-rhel2,ci-test-ppc-rhel1,ci-test-ppc-suse1
PPC_NORMALTEST_G1D3_HOST       =ci-test-ppc-rhel2,ci-test-ppc-rhel1,ci-test-ppc-suse1
PPC_NORMALTEST_STANDALONE_HOST =ci-test-ppc-rhel2

PERFORMANCETEST_TPCC_HOST      =ci-test-pm1,ci-test-pm2,ci-test-pm3

INSTALL_DIR=/opt/sequoiadb
INSTALL_PG_DIR=/opt/SequoiaSQL
CI_WORK_DIR=/tmp/ci
SVCNAME=11810
RELIABILITY_TESTCASE_WORK_DIR=/tmp/ci_reliability

BACKLOG_DIR=/opt/ci/backup_log
JENKINS_HOST=jenkins-master

DOC_HOST=ci-cmpl-doc

TPCC_DBPATH_LIST = /data/disk01/sequoiadb,/data/disk02/sequoiadb,/data/disk03/sequoiadb,/data/disk04/sequoiadb,/data/disk05/sequoiadb,/data/disk06/sequoiadb,/data/disk07/sequoiadb,/data/disk08/sequoiadb,/data/disk09/sequoiadb,/data/disk10/sequoiadb,/data/disk11/sequoiadb,/data/disk12/sequoiadb,
RELIABILITYTEST_DBPATH_LIST=/data/sequoiadb



