#set ulimits, -1 represent unlimited
#no coredump
core_file_size=0
#data seg size,value is -1
data_seg_size=-1
#file size,value is -1
file_size=-1
#virtual memory,value is -1
virtual_memory=-1
#open files,value is 60000
open_files=60000
