instanceName,port,databaseDir,coordAddr
myinst,6101,[installPath]/database/6101,-

# Note: coordAddr, '-' means the first coord in sdb.conf. You can configure it by format hostName1:serviceName1 or [hostname1:serviceName1,hostname2:serviceName2]
