import os
import SCons.Tool.jar
from os.path import join, dirname, abspath

Import("javaEnv")
Import("jarPath")

javaEnv['JAVAC'] = javaEnv['JAVAHOME'] + os.sep + 'bin' + os.sep + 'javac'
javaEnv['JAR'] = javaEnv['JAVAHOME'] + os.sep + 'bin' + os.sep + 'jar'
javaEnv.Execute(Touch('version'))
os.system("echo Release=`svn info ../../ | grep Revision | awk '{print $2}'` > version")
os.system("echo Build_time=`date +'%Y-%m-%d %H:%M:%S'` >> version")
os.system("gcc ../../../../misc/ci/src/compile/print_version.c -o ../../../../misc/ci/src/compile/print_version -I../../../../SequoiaDB/engine/include")
os.system("echo SequoiaDB_version=`../../../../misc/ci/src/compile/print_version` >> version")
javaClasses = javaEnv.Java( '.', 'src/main/java' )
jarCommand = join ( jarPath, "jar -cvf $JARNAME -C $BUILDPATH ." )
myfile = javaEnv.Command ( 'jar.out', [], jarCommand )
javaEnv.AlwaysBuild ( myfile )
