import os

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")

gtestFiles = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc"
      ]

gtestMainFile = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest_main.cc"
      ]

testCommonFiles = [
        "testcommon.cpp","impWorker.cpp",
        "./datasource/DS_thread.cpp"
      ]

testFiles1 = [ "./misc/decimal.cpp" ]

testFiles2 = [ "./misc/numberLong.cpp" ]

testFiles3 = [ "./misc/trunOncache.cpp" ]

testFiles4 = [ "./misc/time.cpp" ] 

testFiles5 = [ "./datasource/DS_InvalidArgTest.cpp" ]

testFiles6 = [ "./datasource/DS_InvalidConnTest.cpp" ]

testFiles7 = [ "./datasource/DS_ConnTest.cpp" ]

testFiles8 = [ "./datasource/DS_ThreadTest.cpp" ]

testFiles9 = [ "./datasource/DS_ChecktimeTest.cpp" ]

testFiles10 = [ "./datasource/DS_ClTest.cpp" ]

testFiles11 = [ "./datasource/DS_InvalidUsrTest.cpp" ]

#testFiles12 = [ "./datasource/DS_CoordTest.cpp" ]

testFiles13 = [ "./misc/lob.cpp" ]

testFiles14 = [ "./misc/code.cpp" ]

testFiles15 = [ "./misc/date.cpp" ]

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)
gtestMainObj = env.Object('gtestMainObj', gtestMainFile)

# dll compile
decimal        = dllBuildEnv.Program("decimal",       [testFiles1, gtestMainObj, testCommonFiles])
numberLong     = dllBuildEnv.Program("numberLong",    [testFiles2, gtestMainObj, testCommonFiles])
trunOncache    = dllBuildEnv.Program("trunOncache",   [testFiles3, gtestMainObj, testCommonFiles])
time           = dllBuildEnv.Program("time",          [testFiles4, gtestMainObj, testCommonFiles])
DS_InvalidArgTest  = dllBuildEnv.Program("DS_InvalidArgTest", [testFiles5, gtestMainObj, testCommonFiles])
DS_InvalidConnTest = dllBuildEnv.Program("DS_InvalidConnTest", [testFiles6, gtestMainObj, testCommonFiles])
DS_ConnTest        = dllBuildEnv.Program("DS_ConnTest", [testFiles7, gtestMainObj, testCommonFiles])
DS_ThreadTest      = dllBuildEnv.Program("DS_ThreadTest", [testFiles8, gtestMainObj,testCommonFiles])
DS_ChecktimeTest   = dllBuildEnv.Program("DS_ChecktimeTest", [testFiles9, gtestMainObj, testCommonFiles])
DS_ClTest          = dllBuildEnv.Program("DS_ClTest", [testFiles10, gtestMainObj, testCommonFiles])
DS_InvalidUsrTest  = dllBuildEnv.Program("DS_InvalidUsrTest", [testFiles11, gtestMainObj, testCommonFiles])  
#DS_CoordTest       = dllBuildEnv.Program("DS_CoordTest", [testFiles12, gtestMainObj, testCommonFiles])    
lob                = dllBuildEnv.Program("lob", [testFiles13, gtestMainObj, testCommonFiles])
code               = dllBuildEnv.Program("code", [testFiles14, gtestMainObj, testCommonFiles])
date               = dllBuildEnv.Program("date", [testFiles15, gtestMainObj, testCommonFiles])

# static compile
# dll compile
decimal.static       = staticBuildEnv.Program("decimal.static",      [testFiles1, gtestMainObj, testCommonFiles])
numberLong.static    = staticBuildEnv.Program("numberLong.static",   [testFiles2, gtestMainObj, testCommonFiles])
trunOncache.static   = staticBuildEnv.Program("trunOncache.static",  [testFiles3, gtestMainObj, testCommonFiles])
time.static          = staticBuildEnv.Program("time.static",         [testFiles4, gtestMainObj, testCommonFiles])
DS_InvalidArgTest.static  = staticBuildEnv.Program("DS_InvalidArgTest.static",[testFiles5, gtestMainObj, testCommonFiles])
DS_InvalidConnTest.static = staticBuildEnv.Program("DS_InvalidConnTest.static",[testFiles6, gtestMainObj, testCommonFiles])
DS_ConnTest.static        = staticBuildEnv.Program("DS_ConnTest.static",[testFiles7, gtestMainObj, testCommonFiles])
DS_ThreadTest.static      = staticBuildEnv.Program("DS_ThreadTest.static",[testFiles8, gtestMainObj,testCommonFiles])
DS_ChecktimeTest.static   = staticBuildEnv.Program("DS_ChecktimeTest.static",[testFiles9, gtestMainObj, testCommonFiles])
DS_ClTest.static          = staticBuildEnv.Program("DS_ClTest.static",[testFiles10, gtestMainObj, testCommonFiles])
DS_InvalidUsrTest.static  = staticBuildEnv.Program("DS_InvalidUsrTest.static",[testFiles11, gtestMainObj, testCommonFiles])
lob.static                = staticBuildEnv.Program("lob.static",[testFiles13, gtestMainObj, testCommonFiles])
code.static               = staticBuildEnv.Program("code.static",[testFiles14, gtestMainObj, testCommonFiles])
date.static               = staticBuildEnv.Program("date.static",[testFiles15, gtestMainObj, testCommonFiles])

# dll compile
env.Install( '#/build_test',[ decimal,numberLong,trunOncache,time,DS_InvalidArgTest,
			                  DS_InvalidConnTest,DS_ConnTest,DS_ThreadTest,DS_ChecktimeTest,DS_ClTest,DS_InvalidUsrTest,
                              lob,code,date ] )

# static compile
env.Install( '#/build_test',[ decimal.static,numberLong.static,trunOncache.static,
							  time.static,DS_InvalidArgTest.static,DS_InvalidConnTest.static,
							  DS_ConnTest.static,DS_ThreadTest.static,DS_ChecktimeTest.static,
							  DS_ClTest.static,DS_InvalidUsrTest.static,lob.static,code.static,date.static ] )

