
# rootsite info
rootsite_url="192.168.17.183:11810"
rootsite_user="sdbadmin"
rootsite_password="sdbadmin1"

# node ports（多个逗号分割）
node_list="9001,9002"

# datasource names（多个逗号分割）
datasource_list="datasource1,datasource2"

# system cs name
system_cs_name="SDB_SCHEDULE_SYSTEM"
# system cs store domain name
system_cs_domain=""
