/*******************************************************************************

   Copyright (C) 2011-Present SequoiaDB Ltd.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Source File Name = codeGenerator.hpp

   Descriptive Name = N/A

   Dependencies: N/A

   Restrictions: N/A

   Change Activity:
   defect Date        Who         Description
   ====== =========== =========== =============================================
          23/07/2025  fangjiabin  Initial Draft

   Last Changed =

*******************************************************************************/
#ifndef FILELIST_GENERATOR_HPP
#define FILELIST_GENERATOR_HPP

#include "../generateInterface.hpp"

/* =============== statement =============== */
#define SPIDER_MONKEY_CODE_STATEMENT "// this file is automatically generated. DO NOT MODIFY IT!"

#define SPIDER_MONKEY_SOURCE_FILE_LIST \
   "error", \
   "sdb",   \
   "help",  \
   "sdbSP", \

#define ENGINE_SPT_PATH       ENGINE_PATH"spt/"
#define JS_IN_CPP_FILE_PATH   ENGINE_SPT_PATH"js_in_cpp.hpp"

class codeGenerator : public generateBase
{
DECLARE_GENERATOR_AUTO_REGISTER() ;

public:
   codeGenerator() ;
   ~codeGenerator() ;
   int init() ;
   bool hasNext() ;
   int outputFile( int id, fileOutStream &fout,
                   string &outputPath ) ;
   const char* name() { return "js code" ; }

private:
   bool _isFinish ;
} ;

#endif
