/*******************************************************************************

   Copyright (C) 2011-Present SequoiaDB Ltd.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Source File Name = dpsTransID.hpp

   Descriptive Name = DPS Transaction ID

   When/how to use: this program may be used on binary and text-formatted
   versions of OSS component. This file contains declare for transaction ID in
   SequoiaDB.

   Dependencies: N/A

   Restrictions: N/A

   Change Activity:
   defect Date        Who Description
   ====== =========== === ==============================================
          11/01/2019  HGM Copied from dpsDef.hpp

   Last Changed =

*******************************************************************************/
#ifndef DPS_TRANS_ID_HPP_
#define DPS_TRANS_ID_HPP_

#include "ossTypes.h"
#include "ossAtomic.hpp"
#include "ossUtil.h"

// node ID of transaction ID
typedef UINT16 DPS_TRANSID_NODEID ;

// serial number of transaction ID
typedef UINT64 DPS_TRANSID_SN ;

typedef ossAtomic64 DPS_TRANSID_SN_ATOMIC ;

// invalid node ID component of transaction ID
#define DPS_INVALID_TRANSID_NODEID  ( 0 )
// invalid serial number component of transaction ID
#define DPS_INVALID_TRANSID_SN      ( 0LL )
// max serial number component of transaction ID
#define DPS_MAX_TRANSID_SN          ( OSS_UINT64_MAX )
/*
   tags in transaction ID
 */

// ROLLBACK ( 0x80 ): means the transaction is rolling back
#define DPS_TRANSID_ROLLBACK_BIT    ( 0x80 )

// FIRSTOP ( 0x40 ): means this is the first operator of transaction
#define DPS_TRANSID_FIRSTOP_BIT     ( 0x40 )

// AUTOCOMMIT ( 0x20 ): means this is an auto-commit transaction
#define DPS_TRANSID_AUTOCOMMIT_BIT  ( 0x20 )

// RBPENDING ( 0x10 ): means the transaction is rollback pending
// NOTE: In rollback phase, unique keys are occupied by other sessions, so the
//       rolling-back transaction will meet duplicated key issues, and need
//       further process to resolve those duplicated key issues
#define DPS_TRANSID_RBPENDING_BIT   ( 0x10 )

// GLOBALTRANS ( 0x01 ): means the transaction is global
#define DPS_TRANSID_GLOBTRANS_BIT   ( 0x01 )

// ************************ transaction ID of V0 ******************************

// use UINT64 as transaction ID of V0
// | node ID | tags   | serial number |
// | 16 bits | 8 bits | 40 bits       |

typedef DPS_TRANSID_SN DPS_TRANS_ID_V0 ;

// shift location of tags for transaction ID of V0
#define DPS_TRANSID_TAG_SHIFT_BITS_V0     ( 40 )
#define DPS_TRANSID_NODEID_SHIFT_BITS_V0  ( 48 )

// mask to get serial number ( without node ID and tags )
#define DPS_TRANSID_SN_BIT_V0       0x000000FFFFFFFFFFLL
// mask to get raw transaction ID ( including node ID and serial number )
#define DPS_TRANSID_VALID_BIT_V0    0xFFFF00FFFFFFFFFFLL
// mask to get tags of transaction ID of V0
#define DPS_TRANSID_TAGS_BIT_V0     0x0000FF0000000000LL

// acquire component of transaction ID of V0
// get node ID from transaction ID of V0
#define DPS_TRANS_GET_NODEID_V0( id ) \
   ( (DPS_TRANS_ID_V0)( id ) >> DPS_TRANSID_NODEID_SHIFT_BITS_V0 )

// get serial number from transaction ID of V0
// NOTE: only contains serial number, without node ID and tags
#define DPS_TRANS_GET_SN_V0( id )      ( ( id ) & DPS_TRANSID_SN_BIT_V0 )

// get tags component from transaction ID of V0
#define DPS_TRANS_GET_TAGS_V0( id )   \
   ( ( ( id ) & DPS_TRANSID_TAGS_BIT_V0 ) >> DPS_TRANSID_TAG_SHIFT_BITS_V0 )

// invalid transaction ID of V0
#define DPS_INVALID_TRANSID_V0 ( DPS_INVALID_TRANSID_SN )

// ************************ transaction ID of V1 ******************************

// _dpsTransID defines the structure of transaction ID ( V1 )
//
// | tags                |                | node ID |
// |        | serial number ( SN )        |         |
// |        | global tag | LTime / raw SN |         |
// | 7 bits | 1 bit      | 56 bits        | 16 bits |

// NOTE:
// - serial number ( must with the global tag ) is used to compare visibility
//   in MVCC, etc
// - if transaction is global, raw serial number is logical time generated by
//   Serial Time Protocol ( measured in microseconds )
// - if transaction is no global, raw serial number is generated by atomic
//   number of transCB
// - obviously, global SN is larger than non-global SN

// shift location of tags for transaction ID of V1
#define DPS_TRANSID_TAG_SHIFT_BITS_V1  ( 56 )

// special value of node ID
// transaction started by local DATA node
#define DPS_TRANSID_LOCAL_NODEID ( 0xFFFF )

// mask to get raw serial number without any tags
#define DPS_TRANSID_RAW_SN_BIT_V1 ( 0x00FFFFFFFFFFFFFFLL )

#define DPS_TRANSID_GLOBTRANS_TAG_V1 \
   ( (DPS_TRANSID_SN)( DPS_TRANSID_GLOBTRANS_BIT ) <<  \
     DPS_TRANSID_TAG_SHIFT_BITS_V1 )

// mask to get global serial number with global transaction tag
#define DPS_TRANSID_GLOB_SN_BIT_V1                       \
   ( DPS_TRANSID_RAW_SN_BIT_V1 | DPS_TRANSID_GLOBTRANS_TAG_V1 )

#pragma pack(1)

/*
   _dpsTransID_v1 defines
 */
// _dpsTransID_v1 is transaction ID of V1
class _dpsTransID_v1
{
public:
   // constructor
   _dpsTransID_v1()
   : _sn( DPS_INVALID_TRANSID_SN ),
     _nodeID( DPS_INVALID_TRANSID_NODEID )
   {
   }

   // copy constructor
   _dpsTransID_v1( const _dpsTransID_v1 &transID )
   : _sn( transID._sn ),
     _nodeID( transID._nodeID )
   {
   }

   _dpsTransID_v1( DPS_TRANSID_SN sn, DPS_TRANSID_NODEID nodeID )
   : _sn( sn ),
     _nodeID( nodeID )
   {
   }

   // assign operator
   OSS_INLINE _dpsTransID_v1 &operator =( const _dpsTransID_v1 &transID )
   {
      _sn = transID._sn ;
      _nodeID = transID._nodeID ;

      return ( *this ) ;
   }

   // compare operators
   OSS_INLINE BOOLEAN operator ==( const _dpsTransID_v1 &transID ) const
   {
      return ( _sn == transID._sn &&
               _nodeID == transID._nodeID ) ;
   }

   OSS_INLINE BOOLEAN operator !=( const _dpsTransID_v1 &transID ) const
   {
      return !( operator ==( transID ) ) ;
   }

   // compare operator, only used for std::map
   OSS_INLINE BOOLEAN operator <( const _dpsTransID_v1 &transID ) const
   {
      BOOLEAN res = FALSE ;
      DPS_TRANSID_SN lGlobSN = getGlobSN() ;
      DPS_TRANSID_SN rGlobSN = transID.getGlobSN() ;

      if ( lGlobSN < rGlobSN )
      {
         res = TRUE ;
      }
      else if ( lGlobSN == rGlobSN )
      {
         res = ( getNodeID() < transID.getNodeID() ) ;
      }
      return res ;
   }

   OSS_INLINE void reset()
   {
      _nodeID = DPS_INVALID_TRANSID_NODEID ;
      _sn = DPS_INVALID_TRANSID_SN ;
   }

   OSS_INLINE BOOLEAN isValid() const
   {
      // for unregister CATALOG, there is no node ID, but it still support
      // transactions, so no need to check node ID
      // but for global transaction, node ID is required
      // NOTE: transCB of COORD and DATA is activated after register to
      //       CATALOG, so they must have node ID
      return ( DPS_INVALID_TRANSID_SN != _sn &&
               ( !isGlobTrans() ||
                 DPS_INVALID_TRANSID_NODEID != _nodeID ) ) ;
   }

   OSS_INLINE BOOLEAN isInvalid() const
   {
      return !isValid() ;
   }

   // get node ID component
   OSS_INLINE DPS_TRANSID_NODEID getNodeID() const
   {
      return _nodeID ;
   }

   // get pointer to node ID ( used by DPS logger )
   OSS_INLINE const DPS_TRANSID_NODEID *getNodeIDPtr() const
   {
      return &_nodeID ;
   }

   OSS_INLINE void setNodeID( const DPS_TRANSID_NODEID &nodeID )
   {
      _nodeID = nodeID ;
   }

   // set rollback tag
   // NOTE: rollback tag could not be cleared
   OSS_INLINE void setRollback()
   {
      _setTag( DPS_TRANSID_ROLLBACK_BIT ) ;
   }

   // test rollback tag
   OSS_INLINE BOOLEAN isRollback() const
   {
      return _testTag( DPS_TRANSID_ROLLBACK_BIT ) ;
   }

   // set first operation tag
   OSS_INLINE void setFirstOp()
   {
      _setTag( DPS_TRANSID_FIRSTOP_BIT ) ;
   }

   // clear first operation tag
   OSS_INLINE void clearFirstOp()
   {
      _clearTag( DPS_TRANSID_FIRSTOP_BIT ) ;
   }

   // test first operation tag
   OSS_INLINE BOOLEAN isFirstOp() const
   {
      return _testTag( DPS_TRANSID_FIRSTOP_BIT ) ;
   }

   // set auto-commit tag
   // NOTE: auto-commit tag could not be cleared
   OSS_INLINE void setAutoCommit()
   {
      _setTag( DPS_TRANSID_AUTOCOMMIT_BIT ) ;
   }

   // test auto-commit tag
   OSS_INLINE BOOLEAN isAutoCommit() const
   {
      return _testTag( DPS_TRANSID_AUTOCOMMIT_BIT ) ;
   }

   // set rollback pending tag
   OSS_INLINE void setRBPending()
   {
      _setTag( DPS_TRANSID_RBPENDING_BIT ) ;
   }

   // clear rollback pending tag
   OSS_INLINE void clearRBPending()
   {
      _clearTag( DPS_TRANSID_RBPENDING_BIT ) ;
   }

   // test rollback pending tag
   OSS_INLINE BOOLEAN isRBPending() const
   {
      return _testTag( DPS_TRANSID_RBPENDING_BIT ) ;
   }

   // set global-transaction tag
   // NOTE: global-transaction tag could not be cleared
   OSS_INLINE void setGlobTrans()
   {
      _setTag( DPS_TRANSID_GLOBTRANS_BIT ) ;
   }

   // test global-transaction tag
   OSS_INLINE BOOLEAN isGlobTrans() const
   {
      return _testTag( DPS_TRANSID_GLOBTRANS_BIT ) ;
   }

   // set serial number with tags
   OSS_INLINE void setSN( DPS_TRANSID_SN sn )
   {
      _sn = sn ;
   }

   // get serial number with tags
   OSS_INLINE DPS_TRANSID_SN getSN() const
   {
      return _sn ;
   }

   // get pointer to serial number ( used by DPS logger )
   OSS_INLINE const DPS_TRANSID_SN *getSNPtr() const
   {
      return &_sn ;
   }

   // reset serial number with given serial number
   // WARNING: will clear all tags
   OSS_INLINE void resetSN( DPS_TRANSID_SN sn )
   {
      _sn = ( sn & DPS_TRANSID_RAW_SN_BIT_V1 ) ;
   }

   // get global serial number with global transaction tag
   OSS_INLINE DPS_TRANSID_SN getGlobSN() const
   {
      return ( _sn & DPS_TRANSID_GLOB_SN_BIT_V1 ) ;
   }

   // get global logical time of transaction ( begin time )
   // NOTE: without any tags, which is the logical time ( in microseconds )
   // WARNING: for non-global transaction, this is only a monotonic value
   OSS_INLINE UINT64 getLogicalTime() const
   {
      return ( _sn & DPS_TRANSID_RAW_SN_BIT_V1 ) ;
   }

   // get original transaction ID
   // including node ID, global tag and logical time, without other tags
   OSS_INLINE _dpsTransID_v1 getOrigTransID() const
   {
      _dpsTransID_v1 rawTransID = ( *this ) ;
      // global transaction tag is needed
      rawTransID._sn = rawTransID.getGlobSN() ;
      return rawTransID ;
   }

   // get transaction ID with rollback tag of current transaction ID
   // NOTE: used in transaction rollback phase
   OSS_INLINE _dpsTransID_v1 getRollbackTransID() const
   {
      _dpsTransID_v1 rollbackTransID = ( *this ) ;
      rollbackTransID.setRollback() ;
      return rollbackTransID ;
   }

   OSS_INLINE void convertFromV0( const DPS_TRANS_ID_V0 &transIDV0 )
   {
      // set node ID
      _nodeID = DPS_TRANS_GET_NODEID_V0( transIDV0 ) ;
      // set serial number
      _sn = DPS_TRANS_GET_SN_V0( transIDV0 ) ;
      // set tags
      _setTag( DPS_TRANS_GET_TAGS_V0( transIDV0 ) ) ;
   }

protected:
   // helper function to set specified tag
   OSS_INLINE void _setTag( DPS_TRANSID_SN tag )
   {
      OSS_BIT_SET( _sn, ( tag << DPS_TRANSID_TAG_SHIFT_BITS_V1 ) ) ;
   }

   // helper function to clear specified tag
   OSS_INLINE void _clearTag( DPS_TRANSID_SN tag )
   {
      OSS_BIT_CLEAR( _sn, ( tag << DPS_TRANSID_TAG_SHIFT_BITS_V1 ) ) ;
   }

   // helper function to test specified tag
   OSS_INLINE BOOLEAN _testTag( DPS_TRANSID_SN tag ) const
   {
      return OSS_BIT_TEST( _sn, ( tag << DPS_TRANSID_TAG_SHIFT_BITS_V1 ) ) ?
             TRUE :
             FALSE ;
   }

protected:
   // serial number ( contains tags and logical time )
   DPS_TRANSID_SN      _sn ;
   // node ID component
   DPS_TRANSID_NODEID  _nodeID ;
} ;

#pragma pack()

// transaction ID of V1
typedef class _dpsTransID_v1 DPS_TRANS_ID_V1 ;

/*
   DPS_TRANS_ID
 */
// transaction ID, currently we are using version 1
typedef DPS_TRANS_ID_V1 DPS_TRANS_ID ;

#define DPS_TRANSID_MIN_GLOB_SN DPS_TRANSID_GLOBTRANS_TAG_V1
#define DPS_TRANSID_MAX_GLOB_SN DPS_TRANSID_GLOB_SN_BIT_V1

// set, get and clear global transaction SN
// NOTE: to process lowTran with UINT64 ( DPS_TRANSID_SN ) is more convenient
//       than transID
#define DPS_SET_TRANSID_SN_GLOBAL( x ) \
      ( OSS_BIT_SET( ( x ), DPS_TRANSID_GLOBTRANS_TAG_V1 ) )

#define DPS_TEST_TRANSID_SN_GLOBAL( x ) \
      ( OSS_BIT_TEST( ( x ), DPS_TRANSID_GLOBTRANS_TAG_V1 ) ? TRUE : FALSE )

#define DPS_CLEAR_TRANSID_SN_GLOBAL( x ) \
      ( OSS_BIT_CLEAR( ( x ), DPS_TRANSID_GLOBTRANS_TAG_V1 ) )

// adjust transaction SN with time error
#define DPS_ADJUST_TRANSID_SN( sn, timeError )                             \
do                                                                         \
{                                                                          \
   if ( DPS_INVALID_TRANSID_SN != ( sn ) &&                                \
        DPS_MAX_TRANSID_SN != ( sn ) &&                                    \
        DPS_TEST_TRANSID_SN_GLOBAL( ( sn ) ) &&                            \
        0 != ( timeError ) )                                               \
   {                                                                       \
      DPS_CLEAR_TRANSID_SN_GLOBAL( sn ) ;                                  \
      if ( ( timeError ) > 0 &&                                            \
           ( sn ) < DPS_MAX_TRANSID_SN - (DPS_TRANSID_SN)( timeError ) )   \
      {                                                                    \
         ( sn ) = ( sn ) + (DPS_TRANSID_SN)( timeError ) ;                 \
      }                                                                    \
      else if ( ( timeError ) < 0 &&                                       \
                ( sn ) > (DPS_TRANSID_SN)( -( timeError ) ) )              \
      {                                                                    \
         ( sn ) = ( sn ) - (DPS_TRANSID_SN)( -( timeError ) ) ;            \
      }                                                                    \
      DPS_SET_TRANSID_SN_GLOBAL( sn ) ;                                    \
   }                                                                       \
} while ( FALSE )

#endif // DPS_TRANS_ID_HPP_
