/*******************************************************************************

   Copyright (C) 2011-Present SequoiaDB Ltd.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Source File Name = optAccessPlan.hpp

   Descriptive Name = Optimizer Access Plan Header

   When/how to use: this program may be used on binary and text-formatted
   versions of Optimizer component. This file contains structure for access
   plan, which is indicating how to run a given query.

   Dependencies: N/A

   Restrictions: N/A

   Change Activity:
   defect Date        Who Description
   ====== =========== === ==============================================
          09/14/2012  TW  Initial Draft

   Last Changed =

*******************************************************************************/
#ifndef OPTACCESSPLAN_HPP__
#define OPTACCESSPLAN_HPP__

#include "core.hpp"
#include "oss.hpp"
#include "rtnPredicate.hpp"
#include "dms.hpp"
#include "mthMatchTree.hpp"
#include "ixm.hpp"
#include "ossAtomic.hpp"
#include "../bson/oid.h"
#include "../bson/bson.h"
#include "ossUtil.hpp"

using namespace bson ;

namespace engine
{
   class _dmsMBContext ;
   class _dmsStorageUnit ;
   class _rtnAccessPlanManager ;

   #define OPT_QUERY_FLAG_WITH_COND     0x00000001
   #define OPT_QUERY_FLAG_WITH_SORT     0x00000002

   enum optScanType
   {
      TBSCAN = 0,
      IXSCAN,
      UNKNOWNSCAN
   } ;

   // note _optAccessPlan object should NEVER been deleted by caller other than
   // _rtnAccessPlanList, user should call getPlan and releasePlan to make sure
   // all plans are properly tracked
   class _optAccessPlan : public SDBObject
   {
   private:
      // index control block for the index that should be used by this plan
      dmsExtentID _indexCBExtent ;
      dmsExtentID _indexLID ;

      OID _indexOID ;         // the oid for the index, for validation
      _mthMatchTree _matcher ;   // matcher that should be used by the plan
      rtnPredicateList *_predList ; // predicate list that generated from
                                    // matcher and index
      _dmsStorageUnit *_su ;        // pointer for the storage unit
      _rtnAccessPlanManager *_apm ; // parent access plan manager

      CHAR _collectionName[ DMS_COLLECTION_NAME_SZ+1 ] ;
      CHAR _idxName[IXM_INDEX_NAME_SIZE + 1] ;

      BSONObj _orderBy ;            // order by called by the user
      BSONObj _query ;              // query condition called by the user
      BSONObj _hint ;               // hint called by the user
      BOOLEAN _hintFailed ;

      INT32 _direction ;            // direction called by the user

      optScanType _scanType ;
      BOOLEAN     _isInitialized ;
      BOOLEAN     _isValid ;

      BOOLEAN _isAutoPlan ;         // auto plan, TRUE when the plan is not
                                    // generated by hint or hint is not valid
      UINT32 _hashValue ;
      ossAtomicSigned32 _useCount ;
      BOOLEAN _sortRequired ; // whether we need to explicit sort the resultset
      BOOLEAN _autoHint ;
   private:
      class _idxEstimateDetail
      {
      public:
         _idxEstimateDetail()
         {
            reset() ;
         }

         void setFlag( INT32 flag )
         {
            _flag |= flag ;
         }

         void setData( INT64 costBase, FLOAT32 queryFactor,
                       FLOAT32 idxUseFactor, FLOAT32 orderFactor,
                       BOOLEAN matchAll )
         {
            _costBase = costBase ;
            _queryFactor = queryFactor ;
            _idxUseFactor = idxUseFactor ;
            _orderFactor = orderFactor ;
            _matchAll = matchAll ;
         }

         void reset()
         {
            _flag = 0 ;
            _costBase = 0 ;
            _matchAll = FALSE ;
            _queryFactor = 1.0 ;
            _idxUseFactor = 1.0 ;
            _orderFactor = 1.0 ;
         }

         BOOLEAN valid() const
         {
            return ( _costBase > 0 ) ;
         }

         /**
          * @brief Compare two estimation details. Smaller is better. Factors
          * are compared by their priorities.
          * @param r Estimation detail compare to.
          */
         BOOLEAN betterThan( _idxEstimateDetail &r )
         {
            if ( _queryFactor < r._queryFactor )
            {
               return TRUE ;
            }
            else if ( _queryFactor > r._queryFactor )
            {
               return FALSE ;
            }
            else if ( _orderFactor < r._orderFactor )
            {
               return TRUE ;
            }
            else if ( _orderFactor > r._orderFactor )
            {
               return FALSE ;
            }
            else if ( _idxUseFactor < r._idxUseFactor )
            {
               return TRUE ;
            }
            else
            {
               return FALSE ;
            }
         }

         /**
          * Whether hit the low bound of cost estimation. If yes, the
          * index is the best index. The result is true when the query condition
          * and the index are full matched, and sort fields full matched if
          * used.
          */
         BOOLEAN hitLowBound() const
         {
            if ( _testFlag( OPT_QUERY_FLAG_WITH_SORT ) )
            {
               if ( _testFlag( OPT_QUERY_FLAG_WITH_COND ) )
               {
                  return _equal( _queryFactor, 0.0 ) &&
                         _equal( _orderFactor, 0.0 ) &&
                         _equal( _idxUseFactor, 0.0 ) ;
               }
               else
               {
                  return _equal( _orderFactor, 0.0 ) ;
               }
            }
            else
            {
               return _equal( _queryFactor, 0.0 ) &&
                      _equal( _idxUseFactor, 0.0 ) ;
            }
         }

         BOOLEAN matchAll() const
         {
            return _matchAll ;
         }

         INT64 getCost()
         {
            return (INT64)( _costBase * _queryFactor *
                            _idxUseFactor * _orderFactor ) ;
         }

      private:
         BOOLEAN _equal( FLOAT32 lhs, FLOAT32 rhs ) const
         {
            return fabs( lhs - rhs ) <= OSS_EPSILON ;
         }

         BOOLEAN _testFlag( INT32 flag ) const
         {
            return _flag & flag ;
         }

      private:
         INT32 _flag ;
         INT64 _costBase ;
         BOOLEAN _matchAll ;
         FLOAT32 _queryFactor ;
         FLOAT32 _idxUseFactor ;
         FLOAT32 _orderFactor ;
      } ;

   private:
      INT32 _optimizeHint ( _dmsMBContext *mbContext,
                            const CHAR *pIndexName,
                            const rtnPredicateSet &predSet ) ;

      INT32 _optimizeHint ( _dmsMBContext *mbContext,
                            const OID &indexOID,
                            const rtnPredicateSet &predSet ) ;

      // caller must hold S latch on the obj
      INT32 _optimizeHint( _dmsMBContext *mbContext,
                           const rtnPredicateSet &predSet ) ;

      // output cost estimation, dir, and indexCBExtent
      INT32 _estimateIndex ( dmsExtentID indexCBExtent, INT32 &dir,
                             _idxEstimateDetail &detail ) ;

      INT32 _estimateIndex ( _dmsMBContext *mbContext, INT32 indexID,
                             INT32 &dir, dmsExtentID &indexCBExtent,
                             _idxEstimateDetail &detail ) ;

      void _estimateTBScan ( INT64 &costEstimation ) ;

      INT32 _useIndex ( dmsExtentID indexCBExtent,
                        INT32 dir,
                        const rtnPredicateSet &predSet,
                        const _idxEstimateDetail &detail ) ;

      INT32 _checkOrderBy() ;

   public :
      _optAccessPlan ( _dmsStorageUnit *su, const CHAR *collectionName,
                       const BSONObj &query, const BSONObj &orderBy,
                       const BSONObj &hint )
      :_useCount(0)
      {
         ossMemset( _idxName, 0, sizeof( _idxName ) ) ;
         ossMemset ( _collectionName, 0, sizeof(_collectionName) ) ;
         ossStrncpy ( _collectionName, collectionName,
                      sizeof(_collectionName) - 1 ) ;

         _isInitialized = FALSE ;
         _scanType = TBSCAN ;
         _indexCBExtent = DMS_INVALID_EXTENT ;
         _indexLID = DMS_INVALID_EXTENT ;
         _su = su ;
         _query = query.copy() ;
         _orderBy = orderBy.copy() ;
         _hint = hint.copy() ;
         _hintFailed = FALSE ;
         _predList = NULL ;
         _hashValue = hash(query, orderBy, hint) ;
         _apm = NULL ;
         _sortRequired = FALSE ;
         _isAutoPlan = FALSE ;
         _autoHint = FALSE ;
      }

      ~_optAccessPlan()
      {
         if ( _useCount.peek() != 0 )
         {
            PD_LOG ( PDWARNING, "Plan[%s] is deleted when use count is "
                     "not 0: %d", toString().c_str(),
                     _useCount.peek() ) ;
         }
         if ( _predList )
         {
            SDB_OSS_DEL _predList ;
         }
      }

      optScanType getScanType()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _scanType ;
      }

      INT32 incCount( INT32 inc = 1 )
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _useCount.add ( inc ) ;
      }

      INT32 decCount( INT32 dec = 1 )
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _useCount.sub ( dec ) ;
      }

      INT32 getCount()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _useCount.peek() ;
      }

      BOOLEAN isHintFailed() const { return _hintFailed ; }

      INT32 optimize() ;

      // matcher and predlist must be used after optimize.
      _mthMatchTree &getMatcher()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _matcher ;
      }

      rtnPredicateList *getPredList ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _predList ;
      }

      INT32 getDirection ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _direction ;
      }

      dmsExtentID getIndexCBExtent () const
      {
         return _indexCBExtent ;
      }

      const CHAR *getIndexName() const
      {
         return _idxName ;
      }

      dmsExtentID getIndexLID () const
      {
         return _indexLID ;
      }

      BOOLEAN Reusable ( const BSONObj &query, const BSONObj &orderBy,
                         const BSONObj &hint ) const ;

      BOOLEAN equal( const _optAccessPlan &right ) const ;

      // get hash result for the plan
      UINT32 hash ()
      {
         return _hashValue ;
      }

      static UINT32 hash ( const BSONObj &query, const BSONObj &orderBy,
                           const BSONObj &hint ) ;

      const CHAR *getName()
      {
         return _collectionName ;
      }

      void setAPM ( _rtnAccessPlanManager *apm )
      {
         _apm = apm ;
      }

      _rtnAccessPlanManager *getAPM()
      {
         return _apm ;
      }

      void release() ;

      BOOLEAN sortRequired() const
      {
         return _sortRequired ;
      }

      void setValid ( BOOLEAN valid )
      {
         _isValid = valid ;
      }

      BOOLEAN getValid () const
      {
         return _isValid ;
      }

      BOOLEAN isAutoGen () const
      {
         return _isAutoPlan ;
      }

      std::string toString() const ;

   } ;
   typedef class _optAccessPlan optAccessPlan ;

}

#endif //OPTACCESSPLAN_HPP__

