system.store.sequoiadb.urls=localhost:11810
system.store.sequoiadb.username=
system.store.sequoiadb.password=DD646136318ECB70BDAD

# sequoiadb connection configure
# connect timeout(ms)
system.store.sequoiadb.connectTimeout=10000
# max auto conntect retry time(ms)
system.store.sequoiadb.maxAutoConnectRetryTime=15000
# set socket timeout(ms)
system.store.sequoiadb.socketTimeout=0
# use nagle or not(true|false)
system.store.sequoiadb.useNagle=false
# use ssl or not(true|false)
system.store.sequoiadb.useSSL=false

# sequoiadb datasource configure
# max connection number
system.store.sequoiadb.maxConnectionNum=500
# increase connection count
system.store.sequoiadb.deltaIncCount=10
# max idle connection number
system.store.sequoiadb.maxIdleNum=2
# keep alive time(ms)
system.store.sequoiadb.keepAliveTime=60000
# check connections period time(ms).
system.store.sequoiadb.recheckCyclePeriod=30000
# check whether the connection is usable(true|false)
system.store.sequoiadb.validateConnection=true
# min idle connection number
system.store.sequoiadb.minIdleNum=0
# update coord address interval(min)
system.store.sequoiadb.syncCoordInterval=0
# options in the session timeout(ms)
system.store.sequoiadb.sessionTimeout=-1
# network block timeout(ms)
system.store.sequoiadb.networkBlockTimeout=6000
# the cache size limit of the session
system.store.sequoiadb.cacheLimit=131072

server.port=8180
spring.application.name=schedule-server
system.jvm.options=-Xmx4096M -Xms4096M
logging.level.com.sequoiadb.datasource.SequoiadbDatasource=WARN