# STP listening port, default is 9622
# port=9622

# STP server list, if not specified, will use host name
# of this machine
# serverlist=

# STP role, default is server
# role=server

# STP synchronize interval in seconds, default is 60
# syncinterval=60

# STP max time error in microseconds, default is 50000
# maxtimeerror=50000

# STP dialog level, default is 3
# Value is 0:PDSEVERE, 1:PDERROR, 2:PDEVENT, 3:PDWARNING, 4:PDINFO, 5:PDDEBUG
# diaglevel=3
